services:
  - type: web
    name: ray-serve-app
    env: python
    buildCommand: pip install -r requirements.txt && python src/train_ray.py
    startCommand: python src/serve_ray.py
    envVars:
      - key: PORT
        fromService:
          type: web
          name: ray-serve-app
          property: port
    healthCheckPath: /predict

